openapi: 3.0.0
info:
  version: 'v1.0'
  title: test-demo-api
  description: test-demo-api
servers:
    - description: Local Host
      url: http://localhost:8005/demo/api
paths:
    /v1.0/authentication/login:
      post:
        tags:
          - 'Login'
        summary: POST authentication
        description: POST authentication
        operationId: postAuthentication
        requestBody:
          content:
            application/json:
              schema:
                properties:
                  username:
                    type: "string"
                    example: "martin"
                  email_address:
                    type: "string"
                    example: "tuongmartin@yopmail.com"
                  password:
                    type: "string"
                    example: "123456"
        responses:
          200:
            description: POST authentication
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/v1PostAuthenticationResponse'
                examples:
                  successExample:
                    $ref: '#/components/examples/v1PostAuthenticationResponse'
                  failExample:
                    $ref: '#/components/examples/v1PostFailAuthenticationResponse'
    
    /v1.0/user/signup:
      post:
        tags:
          - 'Sign Up Account'
        summary: POST sign up account
        description: POST sign up account
        operationId: postSignup
        requestBody:
          content:
            application/json:
              schema:
                properties:
                  username:
                    type: "string"
                    example: "martin"
                  email_address:
                    type: "string"
                    example: "tuongmartin@yopmail.com"
                  password:
                    type: "string"
                    example: "123456"
                  first_name:
                    type: "string"
                    example: "WCH"
                  last_name:
                    type: "string"
                    example: "Jsan"
        responses:
          200:
            description: POST signup
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/v1PostSignupResponse'
                examples:
                  successExample:
                    $ref: '#/components/examples/v1PostSignupResponse'
                  failExample:
                    $ref: '#/components/examples/v1PostFailSignupResponse'
    
    /v1.0/authentication/refresh:
      get:
        tags:
          - 'Refresh'
        summary: GET refresh token
        description: GET refresh token
        operationId: getRefreshToken
        parameters:
          - in: 'header'
            name: token
            required: true
            schema:
              type: string
              example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg4ODU3NTAsImV4cGlyZXNJbiI6NDMyMCwiaXAiOiI6OjEiLCJlbWFpbF9hZGRyZXNzIjoidHVvbmdtYXJ0aW4xMkB5b3BtYWlsLmNvbSIsInVzZXJuYW1lIjoid3d3In0.51aBVVpHZQssHlXQ7kPAQCRP6QlEAGRXNHjm5ykJlGQ
        responses:
          200:
            description: GET refresh
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/v1GetRefreshResponse'
                examples:
                  successExample:
                    $ref: '#/components/examples/v1GetRefreshResponse'
                  failExample:
                    $ref: '#/components/examples/v1GetRefreshFailResponse'
components:
  schemas:
    v1PostAuthenticationResponse:
      type: object
      properties:
        responseData:
          type: "object"
          properties:
            token:
              type: "string"
              example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg0NTk1NDMsImV4cGlyZXNJbiI6NDMyMCwiaXAiOiI6OjEiLCJlbWFpbF9hZGRyZXNzIjoidHVvbmdtYXJ0aW5AeW9wbWFpbC5jb20iLCJ1c2VybmFtZSI6ImRldjIzNCJ9.vpn9BboxknC1DCQNLzSlqI14o5DKrhvqOw6p6scfxR4"
            expiresIn:
              type: number
              example: 4320
            expiryDate:
              type: number
              example: 1618718743
            username:
              type: "string"
              example: "dev234"
            email_address:
              type: "string"
              example: "tuongmartin@yopmail.com"
            first_name:
              type: "string"
              example: "TEST"
            last_name:
              type: "string"
              example: "ABC"
        status:
          description: Success status
          type: "string"
          example: "success"
          enum: ['success','false']
        message:
          description: Response Message
          type: string
          example: null
        timestamp:
          type: "string"
          example: "2019-08-06 02:31:20"
        violations:
          type: 'array'
          items: 
            type: object
          example: []

    v1PostSignupResponse:
      type: object
      properties:
        responseData:
          type: "object"
          properties:
            _id:
              type: "string"
              example: "6077e8a9c4080227c4f84e5d"
            created_date:
              type: "string"
              example: "2021-04-15T04:06:13.207Z"
            updated_date:
              type: "string"
              example: "2021-04-15T04:06:13.207Z"
            username:
              type: "string"
              example: "dev234"
            password:
              type: "string"
              example: "#####"
            email_address:
              type: "string"
              example: "tuongmartin123@yopmail.com"
            first_name:
              type: "string"
              example: "TEST"
            last_name:
              type: "string"
              example: "ABC"
        status:
          description: Success status
          type: "string"
          example: "success"
          enum: ['success','false']
        message:
          description: Response Message
          type: string
          example: null
        timestamp:
          type: "string"
          example: "2019-08-06 02:31:20"
        violations:
          type: 'array'
          items: 
            type: object
          example: []

    v1GetRefreshResponse:
      type: object
      properties:
        responseData:
          type: "object"
          properties:
            token:
              type: "string"
              example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg0NTk1NDMsImV4cGlyZXNJbiI6NDMyMCwiaXAiOiI6OjEiLCJlbWFpbF9hZGRyZXNzIjoidHVvbmdtYXJ0aW5AeW9wbWFpbC5jb20iLCJ1c2VybmFtZSI6ImRldjIzNCJ9.vpn9BboxknC1DCQNLzSlqI14o5DKrhvqOw6p6scfxR4"
            expiresIn:
              type: number
              example: 4320
            expiryDate:
              type: number
              example: 1618718743
            username:
              type: "string"
              example: "dev234"
            email_address:
              type: "string"
              example: "tuongmartin@yopmail.com"
            first_name:
              type: "string"
              example: "TEST"
            last_name:
              type: "string"
              example: "ABC"
        status:
          description: Success status
          type: "string"
          example: "success"
          enum: ['success','false']
        message:
          description: Response Message
          type: string
          example: null
        timestamp:
          type: "string"
          example: "2019-08-06 02:31:20"
        violations:
          type: 'array'
          items: 
            type: object
          example: []

  examples:

    v1PostAuthenticationResponse:
      value:
        message: null,
        responseData:
          token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg4ODU3NTAsImV4cGlyZXNJbiI6NDMyMCwiaXAiOiI6OjEiLCJlbWFpbF9hZGRyZXNzIjoidHVvbmdtYXJ0aW4xMkB5b3BtYWlsLmNvbSIsInVzZXJuYW1lIjoid3d3In0.51aBVVpHZQssHlXQ7kPAQCRP6QlEAGRXNHjm5ykJlGQ"
          expiresIn: 4320
          expiryDate: 1619144950
          username: "www"
          email_address: "tuongmartin12@yopmail.com"
          first_name: "TEST"
          last_name: "ADC"
        status: "success"
        timeStamp: "2021-04-20 02:29:40"
        violations: null

    v1PostFailAuthenticationResponse:
      value:
        message: null
        responseData: null
        status: "fail"
        timeStamp: "2021-04-20 03:10:38"
        violations:
          code: 400
          message: "Authentication failed. Wrong password."
          action: null

    v1PostSignupResponse:
      value:
        message: null
        responseData:
            _id: "607e46b6f56a9751ecb0a340"
            username: "devtest"
            password: "###"
            email_address: "devtest@yopmail.com"
            first_name: "TEST"
            last_name: "ADC"
            created_date: "2021-04-20T03:12:54.204Z"
            updated_date: "2021-04-20T03:12:54.204Z"
            __v: 0
        status: "success"
        timeStamp: "2021-04-20 03:12:54"
        violations: null
    
    v1PostFailSignupResponse:
      value:
        message: null
        responseData: null
        status: "fail"
        timeStamp: "2021-04-20 03:14:58"
        violations:
          code: 400
          message: "A user with this username or email address already exists."
          action: null

    v1GetRefreshResponse:
      value:
        message: null
        responseData:
          token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg4ODY1MTIsImV4cGlyZXNJbiI6NDMyMCwiaXAiOiI6OjEiLCJlbWFpbF9hZGRyZXNzIjoidHVvbmdtYXJ0aW4xMkB5b3BtYWlsLmNvbSIsInVzZXJuYW1lIjoid3d3In0.fryA3qAej8bvKO6EDSvqs7536HRgU_nlxdr-XgvIp9Q"
          expiresIn: 4320
          expiryDate: 1619145712
          username: "www"
          email_address: "tuongmartin12@yopmail.com"
          first_name: "TEST"
          last_name: "ADC"
        status: "success"
        timeStamp: "2021-04-20 03:16:10"
        violations: null

    v1GetRefreshFailResponse:
      value:
        auth: false,
        message: "No token provided."