module.exports = Object.freeze({
    ROUTE_PREFIX: 'demo',
    SALT_WORK_FACTOR:10,
    ALGORITHM: 'aes-256-ctr',
    EXPIRES: 4320,
    MONGO_TIME_ZONE_DEFAULT: -5,
    VERIFICATION_EXPIRES: 24,
    templates: {
        PASSWORD_RESET: 1,
        PASSWORD_RESET_SMS: 2,
        EMAIL_VERIFICATION_CODE: 3,
        EMAIL_VERIFICATION_TOKEN: 4,
        PHONE_VERIFICATION_CODE: 5,
        WELCOME_EMAIL: 6,
        CONTACT_EMAIL: 7,
        INVITATION: 8,
        CONTACT_EMAIL_ADMIN: 9
    },
    variables: {
        FIRST_NAME: "$$FIRST_NAME$$",
        LAST_NAME: "$$LAST_NAME$$",
        EMAIL_ADDRESS: "$$EMAIL_ADDRESS$$",
        USERNAME: "$$USERNAME$$",
        PASSWORD_RESET_HOURS: "$$PASSWORD_RESET_HOURS$$",
        PASSWORD_RESET_URL: "$$PASSWORD_RESET_URL$$",
        PASSWORD_RESET_ID: "$$PASSWORD_RESET_ID$$",
        EMAIL_VERIFICATION_RESET_HOURS: "$$EMAIL_VERIFICATION_RESET_HOURS$$",
        EMAIL_VERIFICATION_URL: "$$EMAIL_VERIFICATION_URL$$",
        EMAIL_VERIFICATION_TOKEN: "$$EMAIL_VERIFICATION_TOKEN$$",
        EMAIL_VERIFICATION_CODE: "$$EMAIL_VERIFICATION_CODE$$",
        INVITATION_ACCEPT_URL: "$$INVITATION_ACCEPT_URL$$",
        INVITATION_TOKEN: "$$INVITATION_TOKEN$$",
        SUBJECT: "$$SUBJECT$$",
        MESSAGE: "$$MESSAGE$$",
        CODE: "$$CODE$$",
        VENDOR_NAME: "$$VENDOR_NAME$$",
        VENDOR_ADDRESS: "$$VENDOR_ADDRESS$$",
        VENDOR_PHONE: "$$VENDOR_PHONE$$"
    },
    mail: {
        PASSWORD_RESET_SUBJECT: "Password Reset",
        EMAIL_WELCOME: "Welcome to Demo!"
    },
    messages: {
        INTERNAL_ERROR: "An internal error has occurred",
        USER_NOT_FOUND: "Authentication failed. User not found.",
        INVALID_PASSWORD: "Authentication failed. Wrong password.",
        NEED_NEW_PASSWORD: "Password needs to be a new password.",
        NO_PASSWORD: "No password provided.",
        USERNAME_EXISTS: "A user with this username already exists.",
        EMAIL_EXISTS: "A user with this email address already exists.",
        UNAUTHORIZED_USER: "Unauthorized user",
        EXISTING_USER: "Username already exists",
        AUTHORIZED: "Authorized",
        INVALID_TOKEN: "Invalid token",
        TOKEN_EXPIRED: "Token has expired",
        INVITATION_REQUEST_ACCEPTED: "Invitation request accepted",
        PASSWORD_RESET_COMPLETE: "Password reset complete",
    }
});
